### PR TITLE
Use lombok to avoid boilerplate code

### PR DESCRIPTION
**Pull request by larsgrefer**

### CODE REVIEW

**Comment by aaschmid** [comment]
I am actually not the biggest fan of lombok and this project the fields are not changing very often such that i do not see the benefit compared to the tradeoffs.

Are you fine with this @larsgrefer?

**Comment by larsgrefer** [comment]
As you like it. This was just a suggestions.

But I'm curious: What are the tradeoffs you're talking about?

**Comment by aaschmid** [comment]
Here are my tradeoffs. Disclaimer: Maybe they are outdated and if so, please tell me ;-)

Development:
* More complex refactoring
* Order of declaration is used for method signatures
* graps deep into the source code
* IDE support not so good
* renaming is more complex

Environment:
* versioning different to standards
* Jacoco/Cobertura/Sonar and so on cannot handle generated code
* javadoc can only be generated from "delomboked" stuff

Also interesting is this blogpost: https://medium.com/@vgonzalo/dont-use-lombok-672418daa819. It has some interesting points...

By the way, another approach is https://immutables.github.io/

**Comment by larsgrefer** [comment]
I'm using IntelliJ IDEA as IDE and have absolutely no problems with refactoring/renamings or IDE support in general. It's all handled transparently.

JaCoCo intentionally ignores all the code generated by Lombok.

The Gradle Plugin I've used here (`io.freefair.lombok`) also reconfigures the `javadoc` Task in order to use the delomboked-sources.

**Pull request closed without merging**
