### PR TITLE
Use Gradles "Task Configuration Avoidance" which requires Gradle >= 4.9

### PR DESCRIPTION
**Pull request by larsgrefer**
I hereby agree to the terms of the Gradle CPD plugin Contributor License Agreement.

### CODE REVIEW

**Comment by aaschmid** [comment]
@larsgrefer thanks for PR. What's the purpose of this change? I tried to have the minimal working Gradle verison in the wrapper and your changes does not require any update here - as far as I could see?

**Comment by larsgrefer** [comment]
Updating to 4.10.3 allows the plugin to be built on Java 11.

**Comment by aaschmid** [comment]
Correct, but the pre-build and provided jar runs with Java 11 and Gradle > 3.5.1. Therefore this is only an issue for the travis-ci build, right?

**Comment by larsgrefer** [comment]
Gradle 3.5.1 is nearly two years old. I thought it might be time to move things a bit forward.

Updating to a newer Gradle version paves the way for new Gradle API's like
- https://docs.gradle.org/current/userguide/lazy_configuration.html
- https://docs.gradle.org/current/userguide/task_configuration_avoidance.html

The Java 11 issue also affected my local machine. I've had to install Java 8 in order to work on #31

**Comment by aaschmid** [comment]
Understood, to work on this plugin you need to have Java 8 right now. To run it Java 11 is perfectly OK. 

Do you have any use-cases for "lazy configuration" and "task configuration avoidance" which you would like to introduce in this plugin?

Travis build: The Java 11 build is unfortunately still broken. Upon first view it seems to be an issue on JaCoCo:
```Caused by: java.lang.NoSuchFieldException: $jacocoAccess```

**Comment by aaschmid** [comment]
Thanks for your effort @larsgrefer. I like the changes and I would like to merge them :-)

Do you have an idea about the Java 11 build problems? Could it be that PMD support Java 11 from 6.6.0 on?

**Comment by aaschmid** [comment]
Hi @larsgrefer, thanks for your PR. Even if creation of `Cpd` tasks is not very expensive it might be a valid feature to use configuration avoidance.

**Pull request merged**
